# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#test config
trigger:
- main

pool:
  name: MyLocal
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: eggplant-runner@2
  inputs:
    daiVersion: '7.3.0-3'
    serverURL: 'http://localhost:8000/'
    testConfig: 'ById'
    testConfigID: 'dfdee5ed-c5cd-4810-9b84-16a02c6ece56'
    clientID: 'client:dai:api:integration:421237e3-6460-46a6-9a87-701038b2f4c7'
    clientSecret: 'iveAflD1twcC8bWxAImy8Ls645bEOvSv'
